
name: CI

on:
  pull_request:
    types: [closed]

jobs:
  build:

    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Test, Build & Deploy

    steps:
      # Set up SSH
      - name: Install SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Test before upload
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start

      # Build & Upload
      - name: Build
        run: npm install && npm run build
      - name: Deploy with rsync
        run: rsync -avz ./dist/ admin@${{ secrets.SSH_HOST }}:/home/admin/vue.victorciurana.com/dist/
